# config file for NoteblockMusicPlayer plugin
# author: opplaypro

regions:
  # WorldGuard region name
  'spawn':
    # list of songs to be played when player is in that region
    songs:
      # all *.nbs files must be in plugins/NoteblockMusicPlayer/songs
      - 'village.nbs'
      - 'ambient.nbs'
    # true if you want to shuffle played songs (recommended true, default true)
    # shuffle set to true ignores loop setting
    shuffle: true
    # true if you want to loop through all songs (recommended true, default true)
    loop: true
    # playlist volume 0-100, integer only (default 100)
    volume: 100

  # second configured region
  'pvp_arena':
    songs:
      - 'fight.nbs'
      - 'arena_ambient.nbs'

    loop: true
    shuffle: true
    volume: 100