name: NBSZonePlayer
main: com.github.opplaypro.nbszoneplayer.NBSZonePlayer
version: ${project.version}
description: Play your own music on the server!
author: opplaypro
depend:
  - NoteBlockAPI
  - WorldGuard
api-version: 1.21

commands:
  nbszoneplayer:
    description: 'test'
    usage: '/<command> reload'
    aliases: [nbszp, nzp]
    permission: nbszoneplayer.command.reload
    permission-message: "ยง4You don't have  ยงc${permission}ยง4 permission to use this command!"
